version: '3.9'

services:
  jlab:
    build: .
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=easy
    ports:
      - 8888:8888
    volumes:
      - ./data/:/home/jovyan/work/data
      - ./notebooks/:/home/jovyan/work/notebooks
    command: start-notebook.sh --ServerApp.password='sha1:dcf97170ed86:b1ce72070dcd762dac904e1cbae93b46b428686f'
